### ISSUE TITLE
Run verifymetrics with Python 3

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/dmg-build-scripts#1]
The python script for checking metrics from the EFU will now need to be run with Python 3. I think it just affects this line:
https://github.com/ess-dmsc/integration-test/blob/master/ansible/integration_test_end.yml#L33

**Comment by mortenjc** [comment]
That's cool. We still have two other issues breaking the integration test so this is not a concern. We will fix this as soon as we get to it.

**Comment by mortenjc** [comment]
issue too old, closing
